# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: 蓝树林服务器玩法帮助
site_description: 蓝树林我的世界服务器所有玩法帮助，带你无障碍玩耍
site_url: https://docs.trees.blue
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 点击切换至正常模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: 点击切换至夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-3
        name: 点击遵循浏览器设置
  font:
    code: Source Code Pro
  language: zh
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/solid/tree
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.tooltips
    - navigation.sections
    - navigation.indexes
plugins:
  - search
  - glightbox
  - macros
copyright: Copyright &copy; 2016 - 2025 蓝树林我的世界服务器
extra:
  social:
    - icon: material/web
      link: https://mc.trees.blue
      name: 服务器官网
    - icon: material/map
      link: https://map.trees.blue
      name: 服务器在线地图
    - icon: simple/github
      link: https://github.com/Jeansou/thebluetreewiki
      name: 提供新玩法帮助
    - icon: fontawesome/solid/coins
      link: https://afdian.com/a/AquaSlate
      name: 赞助服务器
repo_url: https://github.com/Jeansou/thebluetreewiki
repo_name: 玩法帮助项目
nav:
  - 首页: index.md
  - 大厅:
    - lobby/index.md
    - 传送 NPC: lobby/teleport.md
    - 矿区: lobby/mine.md
    - 酒吧: lobby/barman.md
  - 生存:
    - 首页: survival/index.md
    - 酿酒:
      - survival/brewing/index.md
      - "如何酿酒":
        - survival/brewing/brewing.md
        - survival/brewing/aging.md
        - survival/brewing/distilling.md
        - survival/brewing/sealing.md
        - survival/brewing/receipts.md
    - 大型动态门:
      - survival/bigdoors/index.md
      - 建造教程: survival/bigdoors/build.md
    - 魔法系统:
      - survival/magic/index.md
      - 法杖进度: survival/magic/progression.md
      - 法术点: survival/magic/spellpoints.md
      - survival/magic/crafting.md
  - 实用工具:
    - utilities/index.md
    - 盔甲架编辑器: utilities/ArmorStandEditor.md
    - 自动钓鱼: utilities/AutoFishing.md
    - 旗帜制作: utilities/BannerMaker.md
    - 随机传送: utilities/rtp.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - stylesheets/extra.css